# crd-hsj.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hotstandbyjobs.apps.paia.tech
spec:
  group: apps.paia.tech
  scope: Namespaced
  names:
    kind: HotStandbyJob
    plural: hotstandbyjobs
    singular: hotstandbyjob
    shortNames: [hsj]
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources: { status: {} }
      additionalPrinterColumns:
        - name: IdleTarget
          type: integer
          jsonPath: .spec.idleTarget
        - name: Busy
          type: integer
          jsonPath: .status.busyCount
        - name: Total
          type: integer
          jsonPath: .status.desiredReplicas
        - name: Mode
          type: string
          jsonPath: .spec.busyProbe.mode
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["idleTarget","jobTemplate","selector"]
              properties:
                idleTarget:
                  type: integer
                  minimum: 0
                minReplicas:
                  type: integer
                  minimum: 0
                  default: 0
                maxReplicas:
                  type: integer
                  minimum: 1
                  default: 1000
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties: { type: string }
                jobTemplate:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                busyProbe:
                  type: object
                  properties:
                    mode:
                      type: string
                      enum: ["annotation","http","exec"]
                      default: "annotation"
                    annotationKey:
                      type: string
                      default: "paia.tech/busy"
                    http:
                      type: object
                      properties:
                        port: { type: integer, default: 8080 }
                        path: { type: string, default: /busy }
                        successIsBusy: { type: boolean, default: true }
                        timeoutSeconds: { type: integer, minimum: 0, default: 1 }
                        periodSeconds: { type: integer, minimum: 1, default: 10 }
                    exec:
                      type: object
                      properties:
                        command:
                          type: array
                          items: { type: string }
                          minItems: 1
                        container:
                          type: string
                        successIsBusy:
                          type: boolean
                          default: true
                        timeoutSeconds:
                          type: integer
                          minimum: 0
                          default: 1
            status:
              type: object
              properties:
                observedGeneration: { type: integer }
                busyCount: { type: integer }
                idleCount: { type: integer }
                desiredReplicas: { type: integer }
