apiVersion: apps.paia.tech/v1alpha1
kind: HotStandbyJob
metadata:
  name: game-worker3
  namespace: default
spec:
  idleTarget: 20
  minReplicas: 0
  maxReplicas: 100
  scaleDownDelaySeconds: 30

  # Pods to count as capacity:
  selector:
    matchLabels:
      app: game-worker

  # What to run for each unit of capacity:
  jobTemplate:
    parallelism: 1
    backoffLimit: 0
    ttlSecondsAfterFinished: 60
    template:
      metadata:
        labels:
          app: game-worker
      spec:
        restartPolicy: Never
        containers:
        - name: worker
          image: busybox:1.36
          command: [ "/bin/sh", "-c" ]
          args:
          - |
            # echo idle > /tmp/busy_state;
            # flip to busy when you start handling work:
            # echo busy > /tmp/busy_state
            # simulate some work:
            sleep 30

  busyProbe:
    mode: exec
    exec:
      command: [ "cat", "/tmp/busy_state" ]
      timeoutSeconds: 1
      successIsBusy: true
